************************************
** Library name: rnr_gt3_txtest
** Cell name: gt3_xtDriverModel_Wrap
** View name: schematic
************************************
.subckt gt3_xtDriverModel_Wrap
+ AVCC
+ AVSS
+ AVTTTX
+ IP
+ TXBUFDIFFCTRL_2
+ TXBUFDIFFCTRL_1
+ TXBUFDIFFCTRL_0
+ TXDIFFCTRL_2
+ TXDIFFCTRL_1
+ TXDIFFCTRL_0
+ TXN
+ TXP
+ TXPREEMPHASIS_2
+ TXPREEMPHASIS_1
+ TXPREEMPHASIS_0
+ TERMINATION_CTRL_4
+ TERMINATION_CTRL_3
+ TERMINATION_CTRL_2
+ TERMINATION_CTRL_1
+ TERMINATION_CTRL_0
.prot FREELIB
9/X787[Y<bX767[Y%KX57[
4#(9=p[S#$6b02g+s2 3X''-$[oW_\[%'=q'X''-$[oW_\[%'=q[X''-$[oW_\[%'=q/Z
$j)d#tJ>':,/u:XE hD:/ yIg77SoOw_\[%'=Q/x787CT:XEZ$%4TY
87(:\C 'X8D86G2;Rds$%<5Uw[;j4t Qk7336;w *6oh#[2!m[g[%'=Q'z
$j0'9!=='hm\s%X6L.=#29yM781S#0=daj8%s(97F68<)U];;/4zsC6
:''.')9O$>g9cKq[X''.')9O$>g9cKq/X!Jj/O %67<0'90%2lL
F,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<56
9[$,cf;56#$#[99pXfH6k$%Y.U340Q
5AXAT,%W+5m(i74#qW[p.\%Y 3efL
F,w6w24$#[99Pxu[/<9'X8al
F,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<56
BU\-g\ 9e7.4\YqOipJ)4O:5X#$.Z!29[U\.8
X256;>7x -/xL8_jw+J8ZA0'k-[x46_jwf]A:$.:#+N23/_3q
7= 2e7[W+b4I$#Z!29[Ow9k=6xX4yU\WF)iz$#4(+j8za0'K:d6 yY:M;%[O3+#M;ba  U'K+Oip$U\M-%_48U\9F\XMV_.p:00*774;-%_fV#k=69eUyY:O<=ml<7X57%a  U'Oo=ml<7X57ba  U'O<=ml<74d%%a  )2/o=ml<74d%ba  )2/<=ml<7Z#Zra:L
)*P:<x;$.z!29$u\.#TUm0o3+SwI)Ci$,Q=29[FY.:#+N23/7x5O)p\,8dTUR-2,8z(OJC3/.K=69CZ,_d[I=Ci>,9wr%A577$k-[xFv_d[7%$o3+#o<)p\'9*9f\x4:)d(OJC3'y*9f\x4:)z(OJC3'9*9f\xFAsd(OJE![y*9f\xFAsz(OJE![9*9f\xuho%((6
B(8YZW7WD78+/9F\7f')8
<592Zv7t[:B4/[4'/rw72v0:#+w77W#+q
5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[L
F,wfw33G8pw+5M(I74#Qo=a:mz=!-z
[n7G)fRxZG\<]:38g8m'uQoIPj)4oY
a92<4<m:==ot:#k%F2oG%C/Y
a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[n[
+KR->]J74#q=.356k=6xef'7[W[9o269$t:=0M6[
+t'Y=O$U\((9izyx# TW[!T8Z(39cIyx#=2)126dc Z*6Uy=8
oU=MH$2#F:=0m67\kr]xZ>mz9f\72,_x :RAL87\o-=_78o<5<9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQP:00*p74;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)K U/x#$1# <0$289$T:=MD/\%y 9C*,##=-R[28)Q tw[!t8zwIyp*vDx5O=ML<7x5<)p\,8z UR-2,#x(OJCZ,#K=694 Y=#!<)12'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F6=#::5xZt%;4:]0m67*90BML<%#m-D$23_%T:=E*6DC z*6u$u';-%_4:y*9f\x4:9Q;tD6u6\%y:D[4Yy:m+D$o3+#!O)12\9QP:3p*vD4;2oIP$)z(OJEu6\%y:D6Fv_d[IyE 6\%y:D6F/_d[IyEu6\%y:3Gav_d[7N> 6\%y:3Ga/_d[7N>u6\%y:B8!3_jq
7]%280s3P93269$t:]0M67*90bml<%#M-d$23_%t:=e*6dc Z*6U$U';-%_4:Y*9F\X4:9q;Td6U6\%Y:d[4yY:M+d$O3+#!o) 2\9q+:3P*Vd4;2Oip$)Z(ojeU6\%Y:d6fV_D[iYe 6\%Y:d6f/_D[iYeU6\%Y:3gAV_D[7n> 6\%Y:3gA/_D[7n>U6\%Y:b8!3_JQ
H*[ /74#q=.356k=6xef'[
,<:*[ $M:W<03AH8g!!xX Tdc !x8d8!8
<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a90
Nf#=!-6;:2# 'O2.$)cSu5>3w9%#[6
9[$S<=F9[;>06W7WDzg#DUqOipJ)4Oy
a92<4<m:==ot:#k%F2oG%C/Y
a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[n[
+KR->]J74#q==zVb/9F\7f')#$:-X#$.Z!29[U\.8
X256;>7x -/xL8_jw+J8ZA0'k-[x46_jwf]A:$.:#+N23/_3q
7= 2e7[W+*7js7\KR]Xz>MZ9F\72,_X :ral87\O-=_78O<5<9c3V_D[iYPz>,9WiY0*VdX5<=ml<7X i)P\,#X ur-2\Yq+:00*774;-%_fV#k=69eUyY:O<=ml<7X57%a  U'Oo=ml<7X57ba  U'O<=ml<74d%%a  )2/o=ml<74d%ba  )2/<=ml<7Z#Zra:L
)\u:=2'5J#F:=0m67\kr]xZ>mz9f\72,_x :RAL87\o-=_78o<5<9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQP:00*p74;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)*u:<x/$.z!29$u\.#TUm0o3+SwI)Ci$,Q=29[FY.:#+N23/7x5O)p\,8dTUR-2,8z(OJC3/.K=69CZ,_d[I=Ci>,9wr%AH$Rz((9E Yy:oO]ML<74k-%_F/.K=69C3'yQ;tD6Fv.K=69C3'9Q;tD6F/.K=69E![yQ;t3Gav.K=69E![9Q;t3Ga/.K=6907A,Q+Y
3$H$2#$:]0m67*kr]xi>mz9f\72,_xT:RAL67\o-]_78o<5<9C3v_d[Iypi>,9wIy0*vDx5<]ML<7x I)p\,#xTUR-2\yQP:00*p74;-%_Fv.K=69EuYy:o<]ML<7x57%A  u'oO]ML<7x57BA  u'o<]ML<74D%%A  )2/O]ML<74D%BA  )2/<]ML<7z#zRA:l
!< OBxFh6\$+%%g>,9273E0
Nf#)+%Xd 7Z![K83[rc2:%2\H#c2!M[-L
F,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<56
9[$,cf;56#$#[99pX388/d UZ
[n7G)fRxZG\<]:N7).)S)4%6Px4[kO5>0
Nf#Y!*c281k)N90AD0k$ W>0
Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<y
e0mxsW2:N7).)S)4%6Px4[kO5>2G+zk:5-'j%4w%/xa77Gu:kU2WRSw<*I>.B#k9R;g77z)fFd:l
)Cu(93)$-;F:5-'j%4w'\0u$)Cs!=-g>,9273E2,#Q+hi1:$,\((e Jp7\[!=G(:9QPY
8CiY=#=2)1-7Bjw2J8ZA0'k-[z
Fh=Uw['x/5-#$6X7''7[y<BxFh6C 6cML<%4o79CZYX+4(/xL8_jX3'128DC z*6uY=8
_I]AH$,*((e Jp7*[!=G(:9QPY
38J57z)fFd:$-jw'\7'j)#$6B02'4/#+\do3+So73x48_jXp/123#Q+h[%:l
T\[!=G(:9QP:D$*77%T-/bH5X#Ttw[!t8z(36
e77=#K9r;G5703:5-'J%4W'\0U$)cS!=-G>,9273e2,#q+HI1:$,\((E jP[
a TW[!T8Z(39cIy=#=2)1-7bJW2j8za0'K-[Z
Fh=vw<*I>.=#FC9=Pj%So:5-u/74#Qw[P.\%y 3EF$u\((ev:p7% -/bH5X8
_+J8ZA0'k-[x46_3wf]A:z=-+:]_78o<5<) 0
'434:- 2X=0W'\7'J)#$6b02'4/#+\DO3+sO73X48_JxP/123#q+H[%:$#:#+n23/_3Q
$d$*77%t-/Bh5x#tTW[!T8Z(36
e77$#f(93:X7[Y x7f$19K<9e7.4\YqOipJ)4O:d[*P!R+(9izyx+pc/Xz 4\d9Y0*7[
aM2) 23.q+H[%:$.:#+n23/_3Q
7WJ2Xb#fm9[(J=34:5-'J%4W'\0U$)cS+M6j.\%Y 3ef$U\(39izyx+pc/Xz 4\d9Y0*7[
aM2) 23.q+H[%:$.:#+n23/_3Q
7W/280sp3IXUT,HS(93h$192 xe2g+ZK:38G81\;cCml<%4O79czy=#=+)1-7bJQ
$=_78O<5<) 2,.qp:r$*P!3U(9$\H#2);bahL
)KP:k12xX#VrXx;<9zw+o.u>,92:DAJ$,Q+h[%28)QPC9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQ+:00*774;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)Ku:k 2x=#VrXx;<9zw+o.u>,92:DAJ$,Q+h[%28)QPC9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQ+:00*774;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)KH:kU2xJ#VrXx;<9zw+o.u>,92:DAJ$,Q+h[%28)QPC9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQ+:00*774;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)Ki:k%2xB#VrXx;<9zw+o.u>,92:DAJ$,Q+h[%28)QPC9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQ+:00*774;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)K4:k%2xB0w0072G+S2 3xi>mz9f\72,_-wf)1-7B# 7) J$u';-%_4:y*9f\x4:9Q;tD6u6\%y:D[4Yy:m+D$o3+#!O)12\9QP:3p*vD4;2oIP$)z(OJEu6\%y:D6Fv_d[IyE 6\%y:D6F/_d[IyEu6\%y:3Gav_d[7N> 6\%y:3Ga/_d[7N>u6\%y:B8!3_jq
7Ou2[=#f3-Xd\%#$6x7''7*90bml<%#M-'Xlyx+pc9[fy=-WiYP*VdX5o]ml<7X5<)P\,8Ztur-2,#X(ojcz,.k=694 yx#!<) 2'Yq;T3PI>,9W7ba  )Ztur-2,84;-%_4:)Dtur-2,84K-%_4:)Ztur-2'Og;-%_faSDtur-2'OgK-%_faSZtur-2/42=-/Z
F>i#/M93)x7t! 9=Pj%So:]MD/\%y 9C*57%((e J$#4(3'x4:yQ;tD6 6\%y:D6uYy:m;B$o3+#m+DA  u\m2oIP$Rd((94uY=#oO)p\'y*9f\xF/_d[7B$o3+#m;3p*vDx57%$o3+#m;30*vDx57B$o3+#ozkp*vD4D%%$o3+#ozk0*vD4D%B$o3+#k!NI*p[
49(9>:$-Jf:M4'$192 xe26\TKur-'$UqU:ra:Z=-W+3ah57X5o)P\,8Dtur-2,8Z(ojc3/.k=69cz,_D[i=cI>,9WR%a:$rZ(39e yY:Oo]ml<74K-%_f/.k=69c3'Yq;Td6fV.k=69c3'9q;Td6f/.k=69e![Yq;T3gAV.k=69e![9q;T3gA/.k=6907a,q+y
e2Zv9#D udFj0_;;\37G9d$%6
9[$0\;:M_2/r0/!Y>MH%#;9j8zH%cv+EZ
[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,q
5AXlH-'$;<Xzg\<]:Y[3.Os3qxe'T9sQ
5AXAT,%W+5m(i722mCe'TAD56-8;/[
,<:\8(,7\$u*q2/SH)u577[[
,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5AZ
-/R0/.Xx!jJ/o *n :+0#'Bx;<9zw'\7'j)#F!50 :+#;Oy-/h1zk9R;g57d;;\37G9z)fFdHl
Td;;\37G9z)fFd:$43+(9$4:y\*[6
6j$#<2c[u280spm[X17xJx(Oy0
:=# 9xFY$-c$<%6p$]3+(E1Ok[
'3:W :P7\) [%)$]3+(E1Ok[
4#m/X;<9ZW'\7'J)#t(9$h$.-W2UXzT%]h:%P3<-c$<b2lD6-Wo%6pX4[K<*i>.=8
_O%6Px4[k<*I>.X#D udFj0_;;\37G9d$%6
e7s<#to9$ X7[Y x7f$19K<9e7.4\YqOipJ)4O:d[*P!R+(9izyx+pc/Xz 4\d9Y0*7[
aM2) 23.q+H[%:$.:#+n23/_3Q
7WV26U';+f326Y#$6x7''7[Y<bXfH6c 6Cml<%4O79czyx+4(/Xl8_Jx3'10
o#:#+n23/_3Wi]ah$,*((E jP7*[!=g(:9qpy
3MT(70#'Bp3<70#'Bp3<70#'Bp3<7[y<BxZ>mz9f\72,_-wf)1-7B# 7)v2,8d(OJC3v#K=69C3/_d[Iy0Z>,9wI=C*vDx I=ML<7$;-/xm/_jw7%A  )d UR-2'9Q;t30Z>,9wIyE Yy:m;3pZ>,9wIyEuYy:m;30Z>,9w7N> Yy:ozkpZ>,9w7N>uYy:ozk0Z>,9w<wGLYX8
oU=MV$-C$<%6P$19k<937G9d569=P/9# Um0o3+SwI)%23_jX3'x4:yQ;tD6 8\%y:D6uYy:m;B[o3+#m+DA  u\m+oIP$Rd(394uYX#oO)p\'y\9f\xF/_d[7B[o3+#m;3p*vDx57%[o3+#m;30*vDx57B[o3+#ozkp*vD4D%%[o3+#ozk0*vD4D%B[o3+#k!NI*p[
49+O/280spcUXzT%3Um9=p/9#$6b028\TKur-'$UqU:ra:Z># 7)uj$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o)\h$rZ(39e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
3MZ>i# 9X JS7*;[937G9t! 9=P/9# Um0o3+SwI) -p7%((e%s$u';-%_4:y\9f\x4:9Q;tD6u8\%y:D[4Yy:m+D[o3+#!O)12\9Q+:3p*vD4;+oIP$)z(OJEu8\%y:D6Fv_d[IyE 8\%y:D6F/_d[IyEu8\%y:3Gav_d[7N> 8\%y:3Ga/_d[7N>u8\%y:B8!x_3w<wGPj_3w<wGLYX8
oU=M+$#<23u 2x4[k0072G+zk:5-u/7\90BML<%#m-'xLYX+L:=E*)>#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*==#!<) 2'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F>>Yw![1:$192 XE2h=j+:5-u/7\90BML<%#m-'xLYX+PC9[FY>#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*p7$k-[xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO;b#9:-8;/Y'Y:5-U/7[Y<bXz>MZ9F\72,_-WF)1-7b# 7)%:$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o)12\9qp:3P*Vd4;+Oip$)Z(ojeU8\%Y:d6fV_D[iYe 8\%Y:d6f/_D[iYeU8\%Y:3gAV_D[7n> 8\%Y:3gA/_D[7n>U8\%Y:b8!3_JQ
7O[OP7\) [/)$19K<9=p/9#$6b028\TKur-'$UqU:ra:Z=-W+3aS$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o)12\9qp:3P*Vd4;+Oip$)Z(ojeU8\%Y:d6fV_D[iYe 8\%Y:d6f/_D[iYeU8\%Y:3gAV_D[7n> 8\%Y:3gA/_D[7n>U8\%Y:b8!3_JQ
7OuE$-c$<%6p$-c$<%6p$\#$6b028\TKur-'$UqU:ra:Z=-W+3ajP7X5o)P\,8D ur-2,8Z(ojc3/#k=69cz,_D[i=cz>,9WR%a:$rZ(39e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
3MZ>=#F!50 :+#$6B0280SP>ux;<9zw+o.u>,92:DAJ$,Q+h[%28)Qi:D6 Yy:m;%[o3+#m;BA  u'k+oIP$u\m-%_48u\9f\xmv_jwrBAH$)d(OJE 8\%y:30*vD4k+oIP$u'oO)p\,84;+oIP$u'o<)p\,84k+oIP$)2/O)p\'oG;+oIP$)2/<)p\'oGk+oIP$9CDf)10
'\Vp:5-U/7[Y<bX;<9ZW'\0U$#kv<OipJ7X(c9i*P!yW+3aS$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o)12\9qp:3P*Vd4;+Oip$)Z(ojeU8\%Y:d6fV_D[iYe 8\%Y:d6f/_D[iYeU8\%Y:3gAV_D[7n> 8\%Y:3gA/_D[7n>U8\%Y:b8!3_JQ
7O*v$-c$<M4'$.DW'\0U$19K<9[Ow9k=6xX4yb#=-/Bj)7\O-'X4:Yq;Td6 8\%Y:d6UyY:M;b[O3+#M+da  U\M+Oip$rD(*[XM/_3W7%a  )D ur-2'9q;T30z>,9WiYe yY:M;3Pz>,9WiYeUyY:M;30z>,9W7n> yY:OZKPz>,9W7n>UyY:OZK0z>,9W<Wglyx8
oUs12x4[kOy-26y#$6B02G+zk:=MD/\%y 9C*57%((e%s$#4(>9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQ+:00*774;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)K3W9=P/9# 9X JS7[y<Bx;<9zw+o.u>,92:DAJz<#=-'xZ'_Y+:D6 Yy:m;%[o3+#m;BA  u'k+oIP$u\m-%_48u\9f\xmv_jwrBAH$)d(OJE 8\%y:30*vD4k+oIP$u'oO)p\,84;+oIP$u'o<)p\,84k+oIP$)2/O)p\'oG;+oIP$)2/<)p\'oGk+oIP$9CDf)10
'\;h:5-U/70#'bP3<7[Y<bX;<9ZW+O.U>,92:dajZ<#=-'Xz'_y+:d6 yY:M;%[O3+#M;ba  U'K+Oip$U\M-%_48U\9F\XMV_JWRbah$)D(oje 8\%Y:30*Vd4K+Oip$U'Oo)P\,84;+Oip$U'O<)P\,84K+Oip$)2/o)P\'Og;+Oip$)2/<)P\'OgK+Oip$9cdF)10
'\*939=pJ%sO:5-'J%4W'\7'J)#$6x7''7*90bml<%#M-'Xlyx+l:=e*)7X5o)P\,8Dtur-2,8Z(ojc3/.k=69cz,_D[i=cI>,9WR%a:$rZ(39e yY:Oo]ml<74K-%_f/.k=69c3'Yq;Td6fV.k=69c3'9q;Td6f/.k=69e![Yq;T3gAV.k=69e![9q;T3gA/.k=6907a,q+y
3Mi>J#T39[(jB33:5-'j%4w'\7'j)#TUm0o3+SwI)%23_jXE9[FY>#m;%A  u';2oIP$u'k-%_4:9*9f\x48uQ;tD[46\%y:0p*p7$k-[xFv_d[7%$o3+#o<)p\'9*9f\x4:)d(OJC3'y*9f\x4:)z(OJC3'9*9f\xFAsd(OJE![y*9f\xFAsz(OJE![9*9f\xuho%((6
eO6\RW2UXzT%-pm9=pJ%sO:5-'J%4W2O.U>,92:daj$,q+HSXz'_;U:d6 yY:M;%$O3+#M;ba  U'K2Oip$U\M-%_48U*9F\XMV_JWRbah$)D(oje 6\%Y:30*Vd4K2Oip$U'Oo)P\,84;2Oip$U'O<)P\,84K2Oip$)2/o)P\'Og;2Oip$)2/<)P\'OgK2Oip$9cdF)10
'\*9)9=pJ%sO:5-'J%4W'\7'J)#$6x7''7*90bml<%#M-'Xlyx+l:=e*5h#M;%a  U';2Oip$U'K-%_4:9*9F\X48Uq;Td[46\%Y:0P*P7$K-[XfV_D[7%$O3+#O<)P\'9*9F\X4:)D(ojc3'Y*9F\X4:)Z(ojc3'9*9F\XfaSD(oje![Y*9F\XfaSZ(oje![9*9F\XUHO%((6
eO6\JW+*7j7j# 9x%hs7[Y x7f$192 xe26\TKur-'$UqU:ra:Z># 7)uj$U';-%_4:Y*9F\X4:9q;Td6U6\%Y:d[4yY:M+d$O3+#!o)12\9qp:3P*Vd4;2Oip$)Z(ojeU6\%Y:d6fV_D[iYe 6\%Y:d6f/_D[iYeU6\%Y:3gAV_D[7n> 6\%Y:3gA/_D[7n>U6\%Y:b8!3_JQ
7O$O)7*U:=2'5=;W'\7'J)#$6x7''7*90bml<%#M-'Xlyx+l:=e*7$#M;%a  U';2Oip$U'K-%_4:9*9F\X48Uq;Td[46\%Y:0P*P7$K-[XfV_D[7%$O3+#O<)P\'9*9F\X4:)D(ojc3'Y*9F\X4:)Z(ojc3'9*9F\XfaSD(oje![Y*9F\XfaSZ(oje![9*9F\XUHO%((6
eO6\-W2/XzT%-pm9=pJ%sO:5-'J%4W2O.U>,92:daj$,q+HSXz'_yWiYP*VdX5o]ml<7X5<)P\,8Ztur-2,#X(ojcz,.k=694 yx#!<) 2'Yq;T3PI>,9W7ba  )Ztur-2,84;-%_4:)Dtur-2,84K-%_4:)Ztur-2'Og;-%_faSDtur-2'OgK-%_faSZtur-2/42=-/Z
F>.KJ:-8;/m$2:]p280SPCux;<%S279$oW9K=6Xx4Y=++:RA:zBvwIyp*vDx5O]ML<7x5<)p\,8zTUR-2,#x(OJCZ,.K=694 YX#!<)12'yQ;t3pi>,9w7BA  )zTUR-2,84;-%_4:)dTUR-2,84k-%_4:)zTUR-2'oG;-%_FAsdTUR-2'oGk-%_FAszTUR-2/42=-/z
F>Jvw'\7'j)# 9X%HS7[y X7F$192 XE26\tkUR-'$uQuhixLYB# 7)h:$u';-%_4:y*9f\x4:9Q;tD6u6\%y:D[4Yy:m+D$o3+#!O)\H$Rz(39E Yy:oO]ML<74k-%_F/.K=69C3'yQ;tD6Fv.K=69C3'9Q;tD6F/.K=69E![yQ;t3Gav.K=69E![9Q;t3Ga/.K=6907A,Q+Y
3MV(7\) ' )$.dF:5-'j%4w'\7'j)#TUm0o3+SwI)%23_jXC:xZ'_-wIyp*vDx5O]ML<7x5<)p\,8zTUR-2,#x(OJCZ,.K=694 YX#!<) 2'yQ;t3pi>,9w7BA  )zTUR-2,84;-%_4:)dTUR-2,84k-%_4:)zTUR-2'oG;-%_FAsdTUR-2'oGk-%_FAszTUR-2/42=-/z
-t#dk:N7).)S)4%6Px4[kY
a92t#dw0Jxu\-G#;k47j7d)tw[7j4t h6
9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf8
<59I7x8[589[;>06w;=6gA%;q
5AXAT,%W+5m(i722mCe'TA0!TjDhL
F,w6w24$#[99Pxu[/<9'X8al
F,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<56
BU\-g\ 9g's6429>3M d/p:5-A[7[Y<bX787ct:M[2w.#/<-8;/7*;+9$ 67*; /XUV4D=96
9 57[Y<bXA/-c$<9[ HM#$;*=*9!-49! S$.L(3*\:97k(36
9 )7[Y<bX767\;!MX;:0[()E%+T33I:]#*70.+)9m*7[
,;m9=p/9##+9[ HM#$;*=*9!-49! S$.L(3*\:97k(36
eO7b#v+98I$#<2#IXzT%]4:]md/,92:daj$,q+H/*28)qp)94 yx#!<) 2/42=-/Z
F>X#V298Z$#<23sU280SPEuxi>mz=6Xx4YB#=-/b:(7\o-[j2\yQ+:00*77z#zRA:l
sjw0]x;<9zwx'1\K[
gp:M[2g+ZK:7%: ]8
o;$xZt%3LM9.i$19/%9$#/-')<9C*57%(Cev+p7Kk-'xo:_3wUkAH$9CD;)10
'8JW+*7E07T :5-A[7*:<-6(/7X(c9i*5!R4(9mUyb#9;) 2>Sqp:b8!:_JQ
7O[OP7[Y<bX;<9ZWo0mY$19K<9[Ow9k=6xX4yb#=-/Bh57X5o)P\,8D ur-2,8Z(ojc3/#k=69cz,_D[i=cz>,9WR%ah$rZ((9e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
3MZ>=#;roj2G+zk:5-u/7[y<BxZ>mz9f\72,_-wf)1-7B#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*77$k-/xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO8\3U:5-U/7[Y<bX \\;W'\0U$#kv<OipJ7X(c9i*P!3U:d6 yY:M;%[O3+#M;ba  U'K+Oip$U\M-%_48U\9F\XMV_3WRba:$)D(oje 8\%Y:30*Vd4K+Oip$U'Oo)P\,84;+Oip$U'O<)P\,84K+Oip$)2/o)P\'Og;+Oip$)2/<)P\'OgK+Oip$9cdF)10
'\-W<:XzT%3h#9=p/9#$6b028\TKur-'$UqU:ra:Z=-W+3ah;b#M;%a  U';+Oip$U'K-%_4:9\9F\X48Uq;Td[48\%Y:0P*P7$K-[XfV_D[7%[O3+#O<)P\'9\9F\X4:)D(ojc3'Y\9F\X4:)Z(ojc3'9\9F\XfaSD(oje![Y\9F\XfaSZ(oje![9\9F\XUHO%((6
eO8\VW'\0U$19K<9PM><#$6b028\TKur-'$UqU:ra:Z=-WiYP*VdX5o=ml<7X5<)P\,8Z ur-2,#X(ojcz,#k=694 y=#!<)12'Yq;T3Pz>,9W7ba  )Z ur-2,84;-%_4:)D ur-2,84K-%_4:)Z ur-2'Og;-%_faSD ur-2'OgK-%_faSZ ur-2/42=-/Z
F>#KPM9pm>J#$6B02G+zk:5-u/7\90BML<%#m-'xLYX+PC9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQP:00*p74;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)KL:5-u/7[y<Bx \\Uw'\0u$#KV<oIPj7x(C9I*p!3u:D6 Yy:m;%[o3+#m;BA  u'k+oIP$u\m-%_48u\9f\xmv_3wrBA:$)d(OJE 8\%y:30*vD4k+oIP$u'oO)p\,84;+oIP$u'o<)p\,84k+oIP$)2/O)p\'oG;+oIP$)2/<)p\'oGk+oIP$9CDf)10
'\\9m9=p/9#$6b02VrkI:5-U/7\90bml<%#M-'Xlyx+pc9c3V_D[iYPz>,9WiY0*VdX5<=ml<7X i)P\,#X ur-2\Yqp:00*P74;-%_fV#k=69eUyY:O<=ml<7X57%a  U'Oo=ml<7X57ba  U'O<=ml<74d%%a  )2/o=ml<74d%ba  )2/<=ml<7Z#Zra:L
)K U'x \\vw'\0u$19k<9=P/9# Um0o3+SwI)%23_jX3'x4:yQ;tD6 8\%y:D6uYy:m;B[o3+#m+DA  u\m+oIP$Rd(394uYX#oO)p\'y\9f\xF/_d[7B[o3+#m;3p*vDx57%[o3+#m;30*vDx57B[o3+#ozkp*vD4D%%[o3+#ozk0*vD4D%B[o3+#k!NI*p[
49+OV2Vrk4:5-U/7[Y<bX;<9ZW+O.U>,92:daj$,q+H[%2,8D(ojc3V#k=69c3/_D[iY0z>,9Wi=c*VdX i=ml<7$;-[XM/_JW7%a  )D ur-2'9q;T30z>,9WiYe yY:M;3Pz>,9WiYeUyY:M;30z>,9W7n> yY:OZKPz>,9W7n>UyY:OZK0z>,9W<Wglyx8
oU=MHp7d!U'x;<9zw'\0u$19k<9[oW9K=6Xx4YB#=-/bH57x5O)p\,8d UR-2,8z(OJC3/#K=69CZ,_d[I=CZ>,9wr%AH$Rz((9E Yy:oO=ML<74k-%_F/#K=69C3'yQ;tD6Fv#K=69C3'9Q;tD6F/#K=69E![yQ;t3Gav#K=69E![9Q;t3Ga/#K=6907A,Q+Y
3MZ>=3w'\0u$19k<9pm>B#$6B028\tkUR-'$uQu:RA:z=-wIyp*vDx5O=ML<7x5<)p\,8z UR-2,#x(OJCZ,#K=694 Y=#!<)12'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F>i#;ro*2G+zk:5-u/7[y<BxZ>mz9f\72,_-wf)1-7B#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*77$k-/xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
ez97Z3:=2'7$]W<:X;<9ZW+O.U>,92:daj$,q+H[%28)qp#'X4:Yq;Td6 8\%Y:d6UyY:M;b[O3+#M+da  U\M+Oip$rD((94Uy=#Oo)P\'Y\9F\Xf/_D[7b[O3+#M;3P*VdX57%[O3+#M;30*VdX57b[O3+#OZKP*Vd4d%%[O3+#OZK0*Vd4d%b[O3+#K!ni*P[
49+=u280sp)(X;<SgW%b37g9#$6b028\TKF\72,_-WF)1-PI# 7)/2\Yq+:00*77Z#Zra:L
)K +'xZt%3H#9=P/9#$6B02G+zk:=MD/,92:DAJ$,Q+h/*28)Qi:0p*p7$k-[xuho%((6
eO8#3W<UXIV%JW'\0U$19K<9[Ow9%Y 9c*57%((E1t$#4(>94 yx#!<) 2/42=-/Z
F>=jw+*7H*J#kOwpLt7z3:5-u/7\90BIPj7x(C9I*p!jJ:=E*7$#!O)12\9QP:B8!3_jq
7OV2w.#to=XUs7[Y<bXz>MZ=6xX4yb#=-/B:(7\O-:XMV_JWRbah$9cdF)10
'\5W0=XIV.#Km9=p/9# uM0l<%#M-'Xlyx++w9[fyh#!o)12\9qp:b8!3_JQ
7O h$M\W<%8 30#v29=p/9# uM0l<%#M-[Xlyx++w94 yx#!<)12/42=-/Z
F>#\+:=2';<#kOwpLt7z3:5-u/7\90BIPj7x(C9I*p!jJ:=E*7$#!O)12\9QP:B8!3_jq
7=/2w.##+90)$19K<9[Ow9%Y 9c*57%((E1t$#4(32XMV_JWRbah$9cdF)10
'#-W0=X767Z3:5-U/7\90bipJ7X(c9i*P!Jj:=e*7$#!o)12\9qp:b8!3_JQ
7O$:$#<23Su26Y\W'\>A$19/%9$Ow9#M-'Xlyx++w9[fy>JWR%a577$K-[XUHO%((6
eO)7\) (V26Y*W'\>A$19/%9$Ow9#M-'Xlyx++w9[fy>JWR%a577$K-[XUHO%((6
B(8YZWZxuG'%<%[0_\.=8
<592Zv7t[:B4/[4'/rw72v0:#+w77W#+q
5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[L
F,wfw33G8pw+5M(I7' ;cG'S[
,<:K2l37\$u*q2a%;S7x2nXr:[q'Z
[n79#9DxZG\<]:B>>t\[2!kz
[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,q
Hb4/[GsWZxuG'%<%[0_\.b#$6K>2g+ZK:W[2H.#v+9.I$SZf!5026Y\W2%$26Ys+:]P'P-8
_<%8 308
<O[x;<9zw%B37G9# Ow.2G8<$-2bJ00.P>9$<Y=<6(2xoY=8
<O:x;<9zw!]xZv4tw'y2;Y$+up*\H)7*8-[25p$#9-[z
[vX#$6B02h## Ow.2G8<$-2bJ00.P>9$<Y=<6(2xoY=8
oU[%2W###29[(je5w+*7e97*90BIPj7x(C9I*p!jJ:=E*7$#!O)12\9QP:B8!3_jq
7O12w.##+9[(J=yI:=2'7>VW2O.U3+sWi)%23_Jx($Xz'_3h:0P*P7$K-[XUHO%((6
>:$M*W'\0U$]-+T7Z
a77t :5-u/77u(JY0
'8uW+*7h*h#v29=p[S#t8b33T9#M-'Xlyb+4P/XO/_-WuYah$\g(3907a8q+y
36:$#<2#2xD87[y%kxiE9059Bx4YB#=-'b+0X#9<)%2>8QP:o>*77z#zyA:l
)K U/x;<9zw'\0u$y$9)9=P/9# Um0o3+SwI)%23_jX3'x4:yQ;tD6 8\%y:D6uYy:m;B[o3+#m+DA  u\m+oIP$Rd(394uYX#oO)p\'y\9f\xF/_d[7B[o3+#m;3p*vDx57%[o3+#m;30*vDx57B[o3+#ozkp*vD4D%%[o3+#ozk0*vD4D%B[o3+#k!NI*p[
49+O 2Vrkh:5-U/7[Y<bX;<9ZW+O.U>,92:daj$,q+H[%2,8D(ojc3V#k=69c3/_D[iY0z>,9Wi=c*VdX i=ml<7$;-[XM/_JW7%a  )D ur-2'9q;T30z>,9WiYe yY:M;3Pz>,9WiYeUyY:M;30z>,9W7n> yY:OZKPz>,9W7n>UyY:OZK0z>,9W<Wglyx8
oU=MH57[y<Bx;<9zwO0M)$19k<9[oW9K=6Xx4YB#=-/bH57x5O)p\,8d UR-2,8z(OJC3/#K=69CZ,_d[I=CZ>,9wr%AH$Rz((9E Yy:oO=ML<74k-%_F/#K=69C3'yQ;tD6Fv#K=69C3'9Q;tD6F/#K=69E![yQ;t3Gav#K=69E![9Q;t3Ga/#K=6907A,Q+Y
3MJ$9vw+*7H(>#$6B02G+zk:=MD/\%y 9C*57%((e J$#4(3(%2,8d(OJC3v#K=69C3/_d[Iy0Z>,9wI=C*vDx I=ML<7$;-/xm/_3w7%A  )d UR-2'9Q;t30Z>,9wIyE Yy:m;3pZ>,9wIyEuYy:m;30Z>,9w7N> Yy:ozkpZ>,9w7N>uYy:ozk0Z>,9w<wGLYX8
oU=Ms$19k<9=P/9#;rov2G+zk:=MD/\%y 9C*57%((e J$u';-%_4:y\9f\x4:9Q;tD6u8\%y:D[4Yy:m+D[o3+#!O) 2\9Q+:3p*vD4;+oIP$)z(OJEu8\%y:D6Fv_d[IyE 8\%y:D6F/_d[IyEu8\%y:3Gav_d[7N> 8\%y:3Ga/_d[7N>u8\%y:B8!3_jq
7O[O7j#;ROu2g+ZK:5-U/7[Y<bXz>MZ9F\72,_-WF)1-7b#M;%a  U';+Oip$U'K-%_4:9\9F\X48Uq;Td[48\%Y:0P*77$K-/XfV_D[7%[O3+#O<)P\'9\9F\X4:)D(ojc3'Y\9F\X4:)Z(ojc3'9\9F\XfaSD(oje![Y\9F\XfaSZ(oje![9\9F\XUHO%((6
eO*7[Y<bX;<9ZWo0mt$19K<9[Ow9k=6xX4yb#=-/Bh57X5o)P\,8D ur-2,8Z(ojc3/#k=69cz,_D[i=cz>,9WR%ah$rZ((9e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
3MZ>J#$6B02G+zk:%4o)7[y<BxZ>mz9f\72,_-wf)1-7B#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*77$k-/xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO8\-Wo0mS$19K<9=p/9#$6b028\TKur-'$UqU:ra:Z=-WiYP*VdX5o=ml<7X5<)P\,8Z ur-2,#X(ojcz,#k=694 y=#!<)12'Yq;T3Pz>,9W7ba  )Z ur-2,84;-%_4:)D ur-2,84K-%_4:)Z ur-2'Og;-%_faSD ur-2'OgK-%_faSZ ur-2/42=-/Z
F>#K4:%4o07[y<Bx;<9zw'\0u$#KV<oIPj7x(C9I*p!3u:D6 Yy:m;%[o3+#m;BA  u'k+oIP$u\m-%_48u\9f\xmv_3wrBA:$)d(OJE 8\%y:30*vD4k+oIP$u'oO)p\,84;+oIP$u'o<)p\,84k+oIP$)2/O)p\'oG;+oIP$)2/<)p\'oGk+oIP$9CDf)10
'\\93/X \\-W'\0U$19K<9=p/9# uM0O3+sWi)%23_Jx3'X4:Yq;Td6 8\%Y:d6UyY:M;b[O3+#M+da  U\M+Oip$rD(394Uyx#Oo)P\'Y\9F\Xf/_D[7b[O3+#M;3P*VdX57%[O3+#M;30*VdX57b[O3+#OZKP*Vd4d%%[O3+#OZK0*Vd4d%b[O3+#K!ni*P[
49+O h$19K<9=p/9#;RO%2g+ZK:=md/\%Y 9c*57%((E j$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o) 2\9q+:3P*Vd4;+Oip$)Z(ojeU8\%Y:d6fV_D[iYe 8\%Y:d6f/_D[iYeU8\%Y:3gAV_D[7n> 8\%Y:3gA/_D[7n>U8\%Y:b8!3_JQ
7O*2Vrkj:5-U/7[Y<bX;<9ZW+O.U>,92:daj$,q+H[%2,8D(ojc3V#k=69c3/_D[iY0z>,9Wi=c*VdX i=ml<7$;-[XM/_JW7%a  )D ur-2'9q;T30z>,9WiYe yY:M;3Pz>,9WiYeUyY:M;30z>,9W7n> yY:OZKPz>,9W7n>UyY:OZK0z>,9W<Wglyx8
o+2xuS7\) [*V$9vw'\0u$#KV<oIPj7x(C9I*p!3u:=E*7e-wIyp*vDx5O=ML<7x5<)p\,8z UR-2,#x(OJCZ,#K=694 YX#!<) 2'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F>#\u:=2'7iYw2%7:$19k<9=P/9# Um0L<%#m-'xLYX++W9[FYH#!O)12\9QP:B8!3_jq
7O[z77Z3:]P'P7[Y<bX;<9ZW+O.U3+sWi)%23_Jx($Xz'_VWR%a:$rZ(3907a,q+y
3MZ8J# 9X T*7*; /32[90#'Bx;<9zw+o.u3+SwI)%23_jX($xZ'_vwr%A:$Rz(3907A,Q+Y
3MHp7\) [hs$9d#OR22/J#$6B028\tkf\72,_-wf)1-pi# 7) y$Rd((94uY=#k!NI*p[
49P9.I$.D :bu2g+ZK:=md/,92:daj$,q+H/*28)qI:0P*P7$K-[XUHO%((6
eO97T :]PI$9;W'\0U$#kv<r-'$UqU:ra:ZxuW+3aS$rD((94Uy=#K!ni*P[
493[Xd87Z;!%i($M*W'\0U$#kv<r-'$Uqp:ra:ZxuWR%a:$rZ((907a,q+y
3MZ8X# 9Xfy$9d#OR22/J#$6B028\tkf\72,_-wf)1-pi# 7) y$Rd((94uY=#k!NI*p[
4 >9.I$4\W<UX;<9ZW+O.U3+sWi)%23_Jx($Xz'_3h:0P*P7$K-[XUHO%((6
ez57T :W$2/j#$6b028\TKF\72,_-WF)1-PI# 7) Y$rD((94Uy=#K!ni*P[
492/XzT%3l>9$ 87[Y%KX;<SgW2O.U$UqU:ra:ZxuW+3avP7$;-! 2\9qp:b8!3_JQ
7O/280s,)9$ 67[Y%KX;<SgW2O.U$UqU:ra:ZxuW+3avP7$;-! 2\9qp:b8!3_JQ
H*[ /722mCe'TA0!TjDjL
F,w9=p2WD#kr->7:s$# 9p( 4\# w.Zz[
,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5AZ
[n7%#[y=3E7\$U*Q2:#'szXUgj0z2Y
a92[0%=:==ot:#D ud3h#*$O2jF9$%V<Bz
[n79#9DxZG\<]:B>>t\[2!kz
[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,q
Hb4/[GsWZxuG:4\t'%JY'$5=0b0261DW6b0;L
sjw25p280SH:7j: ]8
5(9[(j$#y<B=27$jq
H*[ /722mC678.[;)2eY9,TK<6
9[$0\;:M_2/r0/!Y>MH%#;9j8zH%cv+EZ
[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,q
5AXlH-'$;<Xzg\<]:Y[3.Os3qx2UJ[
,<:K2l37\$u*q2a%;S;W[(/Ykvo*i0
Nf#Y!*c281k)N90AD0k$ W>0
Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<y
e0mxsW2:N7).8C 9BpoWy<=:]= $+zk'6
6:$#<2c9-U/1#Iy
k1261dw+*7J$]U4t7z
-t#dk:N7).8C 9BpoWy<=Y
a92t#dw0Jxu\-G#;k47j7d)tw[7j4t h6
9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf8
<59I7x8[589[;>06w;=6gA%;q
5AXAT,%W+5m(i722mCe'61D;;W-(:[
,<:\8(,7\$u*q2/SH)u577[[
,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5AZ
-/R0/.Xx!jJ/o ]= v8Cy9yx;<9zw%B.m:s<w!=x767t :m$0
'\\9(9>Uwr'/99=p/9#/<M43[0#$6b028\TKur-'$UqU:ra:Z=-W+3aj)7X5o)P\,8D ur-2,8Z(ojc3/#k=69cz,_D[i=cz>,9WR%ah$rZ((9e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
3MJ$m\w!]xa/m$5%*x;<9zw+o.u>,92:DAJ$,Q+h[%28)Q,)9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQP:00*p74;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)K3:m$2h##/<m43[0#$6B028\tkUR-'$uQu:RA:z=-w+3Ae97x5O)p\,8d UR-2,8z(OJC3/#K=69CZ,_d[I=CZ>,9wr%AH$Rz((9E Yy:oO=ML<74k-%_F/#K=69C3'yQ;tD6Fv#K=69C3'9Q;tD6F/#K=69E![yQ;t3Gav#K=69E![9Q;t3Ga/#K=6907A,Q+Y
aps$19k<98i$#d#09=3t1QHh'v(==vw2.AHt3jH:oAHl
Fd3:5-u/7C :=p7W7[595AyzBr)*[/26*QP9!1y$\QPY
e2Zv9#D udFj.[;Oy8Pt88
<592Zv7t[:B4/[4'/rw72v0:#+w77W#+q
5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[L
F,wfw33G8pw+5M(I7' ;cG'S[
,<:K2l37\$u*q2a%;S7x2nV1gQ
5AXpH0XW+5m(i7Z/a*m;J4gQ
5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[L
!z![k,'$oS3Q37(_y[/:5-u/7[y X7F$4t! /x7WRSP:-8;/y[/:k.( DhsC9>DtD:*Q[z
$[m<[tFd:$9[2'B2Ld[
4#cUXUg%[K9r;2/1s$[9=pJ%sO:5-U/74#qW[p.\%Y 3ef$U\((EV:P7% -/Bh5x8
_+J8ZA0'k-[x46_3wf]A:z=-+:]_78o<5<) 0
'4-I:b='g-#K'x=2g+s2 3X;<9ZW7WD78+/9F\7f')#M+)1-0xJWF=a:Z=-+y
8[\h#2);BAH$u*(39IiYX+PC/xi 4\D9y0*7[
4#>'Dj$ST)Tj;G57gfq'X;<%s279=p/9#O!C8z<6k=6xef'7X -/B+Px#=+)1-7bJQ
$=_78O<5<) 2,.qp:r$*P!3U(9$\H#2);bahL
)CiCc 2[m<[tFdH$s0s39=Pj%So:5-u/74#Qw[P.\%y 3EF$u\((ev:p7% -/bH5X8
_+J8ZA0'k-[x46_3wf]A:z=-+:]_78o<5<) 0
'4VUq/XAw0:[aC12[-/+:5-'J%4W'\0U$)cS!=-G>,9273e2,#q+HI1:$,\((E jP[
a TW[!T8Z(39cIy=#=2)1-7bJW2j8za0'K-[Z
FhH;sC9>/.B#/Q'x;<%S279=P/9#o!c8Z<6K=6XEF'7x -/b+pX#=+)1-7Bjq
$=_78O<5<) 2,.qp:r$*P!3U(9$\H#2);bahL
)CiMc 2[-/P:kdH$192 XE2G+zk:38gh#9sUR-'')4wI=A:z<j+:R[*p!3u(6
:z 4\d9Y0*77Xt-[Xl6_Jx3'126dc Z*6Uy=8
o!:Ugp7GFQ/xa.X#$6X7''7[y<BxFh6C 6cML<%4o79CZYX+4(/xL8_jX3'10
o#:#+n23/_3Wi]ah$,*((E jP7*[!=g(:9qpy
3M:$9#D<57;$19k<9=P/9# Um0o3+SwI) -(<#=-/bH57\o-u%:$u';-%_4:y\9f\x4:9Q;tD6u8\%y:D[4Yy:m+D[o3+#!O)12\9QP:3p*vD4;+oIP$)z(OJEu8\%y:D6Fv_d[IyE 8\%y:D6F/_d[IyEu8\%y:3Gav_d[7N> 8\%y:3Ga/_d[7N>u8\%y:B8!3_jq
7O%Y$OZ$ 5XUg%[W'\0U$19K<9[Ow9k=6xX4y=+jP9i*P!3U:=e**7X5o)P\,8D ur-2,8Z(ojc3/#k=69cz,_D[i=cz>,9WR%a:$rZ(39e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
3MJ(7CVrX 2A9[2'902G+zk:=MD/\%y 9C*7!U4:RA:z=-w+3A)5X#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*p7$k-[xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO5>#d<57;$9[2'-X/H1Z;'KX;<9ZW+O.U>,92:dahZIRWF)1-7b# 7)uj$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o)12\9qp:3P*Vd4;+Oip$)Z(ojeU8\%Y:d6fV_D[iYe 8\%Y:d6f/_D[iYeU8\%Y:3gAV_D[7n> 8\%Y:3gA/_D[7n>U8\%Y:b8!3_JQ
7O%S$d#dm'2n$19K<9=p/9# uM0O3+sWi) -(<#=-/Bh57\O-(J2,8D(ojc3V#k=69c3/_D[iY0z>,9Wi=c*VdX i=ml<7$;-/XM/_3W7%a  )D ur-2'9q;T30z>,9WiYe yY:M;3Pz>,9WiYeUyY:M;30z>,9W7n> yY:OZKPz>,9W7n>UyY:OZK0z>,9W<Wglyx8
oU'U2G70#'Bp;[7[y<Bx;<9zw+o.u>,92:DAHzirwf)1-7B# 7) J9H#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*p7$k-[xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO5b#f[9g)57[Y<bX;<9ZW+O.U>,92:dahZIRWF)1-7b# 7)FY$U';-%_4:Y\9F\X4:9q;Td6U8\%Y:d[4yY:M+d[O3+#!o)12\9qp:3P*Vd4;+Oip$)Z(ojeU8\%Y:d6fV_D[iYe 8\%Y:d6f/_D[iYeU8\%Y:3gAV_D[7n> 8\%Y:3gA/_D[7n>U8\%Y:b8!3_JQ
7O%:$-#d):X;<9ZW'\0U$#kv<OipJ7X(3E*+$,q+H[%28)qp#'X4:Yq;Td6 8\%Y:d6UyY:M;b[O3+#M+da  U\M+Oip$rD((94Uy=#Oo)P\'Y\9F\Xf/_D[7b[O3+#M;3P*VdX57%[O3+#M;30*VdX57b[O3+#OZKP*Vd4d%%[O3+#OZK0*Vd4d%b[O3+#K!ni*P[
49cIX!$O3h9>X;<9ZW'\0U$#kv<OipJ7X(3E*+$,q+H[%28)qIe9c3V_D[iYPz>,9WiY0*VdX5<=ml<7X i)P\,#X ur-2\Yq+:00*774;-%_fV#k=69eUyY:O<=ml<7X57%a  U'Oo=ml<7X57ba  U'O<=ml<74d%%a  )2/o=ml<74d%ba  )2/<=ml<7Z#Zra:L
)KP#922A$v)49=P/9#$6B028\tkUR-'$uQPh$v23_jX3'xZ'_3,C9C3v_d[IypZ>,9wIy0*vDx5<=ML<7x I)p\,#x UR-2\yQ+:00*774;-%_Fv#K=69EuYy:o<=ML<7x57%A  u'oO=ML<7x57BA  u'o<=ML<74D%%A  )2/O=ML<74D%BA  )2/<=ML<7z#zRA:l
)Ku39p2A=5w'\0u$19k<9[oW9K=6Xx4Y=+Jp9I*p!3u:=E*)>#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*p7$k-[xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO7=##007:$O5I9>X($19K<9[Ow9k=6xX4y=+jP9i*P!3U:=e*7E-WiYP*VdX5o=ml<7X5<)P\,8Z ur-2,#X(ojcz,#k=694 yx#!<) 2'Yq;T3Pz>,9W7ba  )Z ur-2,84;-%_4:)D ur-2,84K-%_4:)Z ur-2'Og;-%_faSD ur-2'OgK-%_faSZ ur-2/42=-/Z
F>=rwzu%2[63w'\0u$19k<9[oW9K=6Xx4Y=+Jp9I*p!3u:=E**7x5O)p\,8d UR-2,8z(OJC3/#K=69CZ,_d[I=CZ>,9wr%A:$Rz(39E Yy:oO=ML<74k-%_F/#K=69C3'yQ;tD6Fv#K=69C3'9Q;tD6F/#K=69E![yQ;t3Gav#K=69E![9Q;t3Ga/#K=6907A,Q+Y
3[T$o5i:kdJ$19k<9=P/9# Um0o3+SwI) -(<#=-/bH57\o-sx4:yQ;tD6 8\%y:D6uYy:m;B[o3+#m+DA  u\m+oIP$Rd((94uY=#oO)p\'y\9f\xF/_d[7B[o3+#m;3p*vDx57%[o3+#m;30*vDx57B[o3+#ozkp*vD4D%%[o3+#ozk0*vD4D%B[o3+#k!NI*p[
493:X7wrsp:nJS$-#$6b028\TKur-'$UqpH$V23_Jx3'Xz'_3,c9c3V_D[iYPz>,9WiY0*VdX5<=ml<7X i)P\,#X ur-2\Yq+:00*774;-%_fV#k=69eUyY:O<=ml<7X57%a  U'Oo=ml<7X57ba  U'O<=ml<74d%%a  )2/o=ml<74d%ba  )2/<=ml<7Z#Zra:L
)KP)9GH97Gs(9=P/9#$6B028\tkUR-'$uQPh$v23_jX3'xZ'_YwIyp*vDx5O=ML<7x5<)p\,8z UR-2,#x(OJCZ,#K=694 YX#!<) 2'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F>=-w!m4'772P)9p2G+zk:=MD/\%y 9C*7!U4:RA:z=-w+3As*7x5O)p\,8d UR-2,8z(OJC3/#K=69CZ,_d[I=CZ>,9wr%A:$Rz(39E Yy:oO=ML<74k-%_F/#K=69C3'yQ;tD6Fv#K=69C3'9Q;tD6F/#K=69E![yQ;t3Gav#K=69E![9Q;t3Ga/#K=6907A,Q+Y
3MT$o;u:k3g770#'Bp;[7[y<BxZ>mz9f\72,_3XWixLYX+PC9[FY=5wIyp*vDx5O=ML<7x5<)p\,8z UR-2,#x(OJCZ,#K=694 YX#!<) 2'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F>=;w!m4'7723C93/$19k<9[oW9K=6Xx4Y=+Jp9I*p!3u:=E*;$#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*p7$k-[xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO*72p)9>/.x#f!50 gS#$6b028\TKur-'$UqpH$V23_Jx3'Xz'_yWiYP*VdX5o=ml<7X5<)P\,8Z ur-2,#X(ojcz,#k=694 yx#!<) 2'Yq;T3Pz>,9W7ba  )Z ur-2,84;-%_4:)D ur-2,84K-%_4:)Z ur-2'Og;-%_faSD ur-2'OgK-%_faSZ ur-2/42=-/Z
F>=Uwz2/(_7GFQ'x;<9zw'\0u$#KV<oIPj7x(3e*+$,Q+h[%28)QL:D6 Yy:m;%[o3+#m;BA  u'k+oIP$u\m-%_48u\9f\xmv_jwrBAH$)d(OJE 8\%y:30*vD4k+oIP$u'oO)p\,84;+oIP$u'o<)p\,84k+oIP$)2/O)p\'oG;+oIP$)2/<)p\'oGk+oIP$9CDf)10
'\VWZ2/2[-/U:-8;/Y[/:5-U/7\90bml<%#M-[Bt07%((E j$#4(m'X4:Yq;Td6 8\%Y:d6UyY:M;b[O3+#M+da  U\M+Oip$rD((94Uy=#Oo)P\'Y\9F\Xf/_D[7b[O3+#M;3P*VdX57%[O3+#M;30*VdX57b[O3+#OZKP*Vd4d%%[O3+#OZK0*Vd4d%b[O3+#K!ni*P[
493SX7wrsp:-8;/Y[/:5X;<9ZW+O.U>,92:dahZIRWF)1-7b# 7) j9h#M;%a  U';+Oip$U'K-%_4:9\9F\X48Uq;Td[48\%Y:0P*P7$K-[XfV_D[7%[O3+#O<)P\'9\9F\X4:)D(ojc3'Y\9F\X4:)Z(ojc3'9\9F\XfaSD(oje![Y\9F\XfaSZ(oje![9\9F\XUHO%((6
eOs72p)*N2[-/+:5-U/7[Y<bXz>MZ9F\72,_3xwIXlyx+pc9[fy>#M;%a  U';+Oip$U'K-%_4:9\9F\X48Uq;Td[48\%Y:0P*P7$K-[XfV_D[7%[O3+#O<)P\'9\9F\X4:)D(ojc3'Y\9F\X4:)Z(ojc3'9\9F\XfaSD(oje![Y\9F\XfaSZ(oje![9\9F\XUHO%((6
eO0723c*N2[-/p:5-U/7[Y<bXz>MZ9F\72,_3xwIXlyx+pc9[fy>#M;%a  U';+Oip$U'K-%_4:9\9F\X48Uq;Td[48\%Y:0P*P7$K-[XfV_D[7%[O3+#O<)P\'9\9F\X4:)D(ojc3'Y\9F\X4:)Z(ojc3'9\9F\XfaSD(oje![Y\9F\XfaSZ(oje![9\9F\XUHO%((6
eO;72p)*N2[6JW[W=UV1gW'\0U$#kv<OipJ7X(3E*+$,q+H[%28)ql:d6 yY:M;%[O3+#M;ba  U'K+Oip$U\M-%_48U\9F\XMV_JWRbah$)D(oje 8\%Y:30*Vd4K+Oip$U'Oo)P\,84;+Oip$U'O<)P\,84K+Oip$)2/o)P\'Og;+Oip$)2/<)P\'OgK+Oip$9cdF)10
'\5WZ2/(_7gSc937g9D$%9=p/9# uM0O3+sWi) -(<#=-/Bh57\O-U%2,8D(ojc3V#k=69c3/_D[iY0z>,9Wi=c*VdX i=ml<7$;-/XM/_3W7%a  )D ur-2'9q;T30z>,9WiYe yY:M;3Pz>,9WiYeUyY:M;30z>,9W7n> yY:OZKPz>,9W7n>UyY:OZK0z>,9W<Wglyx8
oU[12AJ-)49>g770#'Bp;[7[y<BxZ>mz9f\72,_3XWixLYX+PC9[FY=5wIyp*vDx5O=ML<7x5<)p\,8z UR-2,#x(OJCZ,#K=694 YX#!<) 2'yQ;t3pZ>,9w7BA  )z UR-2,84;-%_4:)d UR-2,84k-%_4:)z UR-2'oG;-%_FAsd UR-2'oGk-%_FAsz UR-2/42=-/z
F>=##007:$o;u9>x\$19k<9[oW9K=6Xx4Y=+Jp9I*p!3u:=E*;$#m;%A  u';+oIP$u'k-%_4:9\9f\x48uQ;tD[48\%y:0p*p7$k-[xFv_d[7%[o3+#o<)p\'9\9f\x4:)d(OJC3'y\9f\x4:)z(OJC3'9\9f\xFAsd(OJE![y\9f\xFAsz(OJE![9\9f\xuho%((6
eO57cvRx12a=5)49g2g+ZK:=md/\%Y 9c*7!u4:ra:Z=-W+3aS*7X5o)P\,8D ur-2,8Z(ojc3/#k=69cz,_D[i=cz>,9WR%a:$rZ(39e yY:Oo=ml<74K-%_f/#k=69c3'Yq;Td6fV#k=69c3'9q;Td6f/#k=69e![Yq;T3gAV#k=69e![9q;T3gA/#k=6907a,q+y
e2Zv9#D udFj0_;'kz
[n7< O9.\$9$F%w6a\4SwO*_784S#0=b0
Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<y
a923405'yO281K)n96Z:622M6
9[$S<=F9[;>06WZxuG'%*50n7(:\8
<59-7tu# 'o2.$9G*9o='hs8
<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a90
Z9$f%472a%;S7x$3wOs);OX;<9ZW'\7'J)#vRxX3[%'=aC/2:Ss5FfD)$8g2;r;G57'/ Yi>.=8
_;k733//+Y
3MT$8/u:y>':,0sC9=Pj%So:5-'j%4w2o.u>,92:DAJz<#=-/bH57\o-'12,8d(OJC3v.K=69C3/_d[Iy0i>,9wI=C*vDx I]ML<7$;-/xm/_3w7%A  )dTUR-2'9Q;t30i>,9wIyE Yy:m;3pi>,9wIyEuYy:m;30i>,9w7N> Yy:ozkpi>,9w7N>uYy:ozk0i>,9w<wGLYX8
oUsx3.=#5%X6Lx63w'\7'j)#$6X7''7*90BML<%#m-'b+$,Q+h[%28)QP(9C3v_d[Iypi>,9wIy0*vDx5<]ML<7x I)p\,#xTUR-2\yQ+:00*774;-%_Fv.K=69EuYy:o<]ML<7x57%A  u'oO]ML<7x57BA  u'o<]ML<74D%%A  )2/O]ML<74D%BA  )2/<]ML<7z#zRA:l
)K4:yd)$8G2;R3gS7[y X7F$192 XE26\tkUR-'$uQuhixLYX+PC9[FYHjwIyp*vDx5O]ML<7x5<)p\,8zTUR-2,#x(OJCZ,.K=694 YX#!<) 2'yQ;t3pi>,9w7BA  )zTUR-2,84;-%_4:)dTUR-2,84k-%_4:)zTUR-2'oG;-%_FAsdTUR-2'oGk-%_FAszTUR-2/42=-/z
F>e#5Q/x3[%'=[c12G+S2 3x;<%S279$oW9K=6Xx4YB+4:RA:z=-w+3A+$u';-%_4:y*9f\x4:9Q;tD6u6\%y:D[4Yy:m+D$o3+#!O) 2\9Q+:3p*vD4;2oIP$)z(OJEu6\%y:D6Fv_d[IyE 6\%y:D6F/_d[IyEu6\%y:3Gav_d[7N> 6\%y:3Ga/_d[7N>u6\%y:B8!3_jq
7O/2:6VW;K733-/I:5-'J%4W'\7'J)#tuM0O3+sWi)%-07%((E j$#4(e/X4:Yq;Td6 6\%Y:d6UyY:M;b$O3+#M+da  U\M2Oip$rD((94Uy=#Oo)P\'Y*9F\Xf/_D[7b$O3+#M;3P*VdX57%$O3+#M;30*VdX57b$O3+#OZKP*Vd4d%%$O3+#OZK0*Vd4d%b$O3+#K!ni*P[
45%x6lH#9S>96AJ8%*q:X3[%'=[C/2g+s2 3X;<9ZW7WD78+/9F\7f')#M+) 0
o,\((E jP7\[!=g(:9qU(9cIyb#=2)1-7bJW2j8za0'K-'10
'8g2;r8z<6;W;K733//3:Y>':,0Sm9=pJ%sO:5-U/74#qW[p.\%Y 3ef$U\(36
:l8_Jx3'128dc Z*6UybJWi]aj$,*((E jP7*[!=g(:9qU(6
e3[%'=!=-G57'/ Yi>.b#5%x6lX6-W'\7'J)#$6b02'4/#+\DO3+sO73X48_3Q
$r[*P!3U(9[\H#2);bajP7Xt-'Xl6_Jx3'126dc Z*6UybJQ
7Y>':,c 6C 2:Ss5FfDh$8g2;r3G77[Y x7f$19K<9e7.4\YqOipJ)4O:d[*7[
a=+)1-7bJW+j8za0'K-'12,.qU:r$*P!3U(9$\H#2);bajP[
45%x6lH#9S(96AJ8%*q/X3[%'=[C12g+s2 3X;<9ZW7WD78+/9F\7f')#M+) 0
o,\((E jP7\[!=g(:9qU(9cIyb#=2)1-7bJW2j8za0'K-'10
'8VW;C/2wrsW'\7'J)#t8b33T9#M-'Xly=Jx3S12>9qp)9m3y=#9%) 2/425-/Z
F:=#5Q[xD\%#$6X7''7*:<-6(/7x(C9I*7X+PE/xo/_-wUyAH$\G(3907A8Q+Y
36J$8/u:m4'$192 XE262zF;*02,_-wf) :z=Y+:o0*)7K5-[xo[_3w<wG3YX8
o;/x3.X#VrXx;<%S279$#/-')<9C*57%(3/bH*X#9<) 2>8QP:o>*77z#zyA:l
)'4:5-'j%4w0072G+S2 3xiE9059Bx4YB#=-[1-7>jwUBAH(7K5-[xo[_3w<wG3YX8
o;ux3.J#VrXx;<%S279$#/-')<9C*57%(3/bH*X#9<)h2>8QP:o>*77z#zyA:l
!< OBx!jJ/o ]6DA%<5U6
9[$0\;:M_2/r0/!Y>MH%#;9j8zH%cv+EZ
[nF,<5a9[nF,<5a9[nF,<5a9[nF,<5a9[nF,q
5AXlH-'$;<Xzg\<]:Y[3.Os3qxe'T9sQ
5AXAT,%W+5m(i722mCe'V8cY9YmdV0%Q
5AXpH0XW+5m(i7Z/a*m;J4gQ
5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[Nf,<5A9[L
!z![k,'$oS3Q37 :49);o. t,#$6k>2G+zk:5-'j%4w[w=uxR:[<*I>.B#F!50/\D:k9R;g7[
af!50/\d:K9r;GP70#'bP3<9<=aC%2X4[KoY-UT,HS3937g9D56b2lD6JW!=X76[
avRx[2wrst:Y>':,HS>96AJ8%*qUX3[%'=aC%2:Ss5FfDh$8g2;r;GP7s/0*_\D6-Q
$x>dTd:*q[X'[M<[TfD:L
)CLM9=P/9#$6X7''70#'Bp3<70#'Bp3<9<=Ac%2x4[kOy-ut,hs3937G9d56B2Ld6jq
$=2'Pj5W'\7'J)#d UDfJ0_;;\37g98
o!s/2G+zk:5-'j%4w[w=uxR:[:-8;/-$[tB2Ld6-w[w=uxR:[<*I>.=#F!50/\D:k9R;gp[
a 9x )07[Y x7f$Os3q37(_Y'Y[W=UL
+jw!B6a$19k<9v0
[=##2[X;<9ZWX[$1L
s-w!= 2G+zk:7 iK[
'p:W[2H#3Wc/Z
357\) / )*7Gk006at63w(6
6:$4*W!] 25x8
5M9[(jX33W9>uWR'/9c12p[
<p:W$:$19K<9P(31PW!] 2g+ZK:xP*k%0# 7Z
(p7C (9=P/9#;9R=#$4\P:5-u/7S;-77/h%7q
![X7/8gW+*7:s$#r3/1Mk[
c+:W03[7\) [u+$]3+(0y0
'-$[T[Dh$19/%9=p/9##+[X76=#f+C 2X./p:-8;/-$[T9=p/9#$6b02g+ZK:5-U/[
ad UDfJ0_fRj_G7[
4fRj_h.x#$6K>2g+ZK:W[h$4*p:-[G770tq[X/H1ZfRj_2g+ZK:5-U/7[Y<bX;<9ZQ
$n7).)s)4-4\ 63Q
7-4\ x#$6K>2g+ZK:W[:$4*+:-[GP70tq/X/H1ZfRj_2g+ZK:5-U/7[Y<bX;<SgW'\0UL
T22McE'ta0!tJdJl
)Cu>9.mj##$6B02A%;s;w[iGy5H72jLW9zq
7W%)$M$229=p/9#d UD3H#*$o2Jf9$%v<bZ
Ft9dPQ[xD\%*w'\0u$oS3Qy8Zt9d90%2Ll
)<kO[d:$m$229=P/9#D ud3h#<kOo. t,8
o9BpJ.=#VrX[2G+zk:N7).8C 9BpoWy<=Y
32uvB/+:m4'87[y<Bx!jJ/5!=2uv\t;9Rz
[v=;w007i$192 XE26yCV:56(G_-X(u%y50.P39$<Yi+3)*\:07K(36
9 (7[Y<bXd\%\W+%8d$1')')J-(j;l9! j$.L(cE/)*0.+P9m*7[
,;#9.MJ##$6x7''7*;!MX;:0[(cE1)5$-)*[ 26*qjHUJ(=xRWu) 0
NY3U:5-U/7T! ]XzV4TW'Y2;y$+jmUH(==-W2.ajZh;l9!1+$\qpy
3p3<=/P:5-u/7Gk006at63w[=dH$-*s39.mj##VrX$2A%;s7X$;vy'#6*60
'Y'Y3C12g+ZK:K0d\8g)q[X/863W[]Dh$M$2+9.MJ.#d UDfJ.[;oY8pT88
oOy-:$19k<9>uWR'/9c12x#/+:-$gp7t! ]xD\%\wzXUg'%*$O%67<0'q
7%=A$19K<9=pJ%sO:=2'P=;j:=2'P=;l:-8;/Y'Y:x>dTd:*q'X'[M<[TfDh$%gv9j_>.x8
_'\7'j)#D udFj0_;'kz
Fh$-w'\0u$192 XE2WRS :y>':,hs>96aj8%*Qux3[%'=Ac%2:sS5fFdH$8G2;R;gp[
ad UDfJ.'vZx23>[
4#)UX;<9ZW'\7'J)#vRx$2:Ss5FfDS$8g2;r;Gs7'/ Yi>.b#5%x6lD63W;K733//+y
8G'S6422y.!j0'9Y
k12WRST:5-u/77H(/_1l
s3u:m4'87[y<Bx19Xj[x6
B(8YZWZxuG'%D5!\23>MD)F6
9[$0\;:M_2/r0/!Y>MH%#;9j8zH%cv+EZ
-\#*50Xz
.ends gt3_xtDriverModel_Wrap
** End of subcircuit definition.
