** End of subcircuit definition.
************************************
** Library name: rnr_spice_sanjay
** Cell name: iob_outlogic_sim_inp
** View name: schematic
************************************
.subckt iob_outlogic_sim_inp cbnet<38> cbnet<37> cbnet<36> cbnet<35>
+cbnet<34> cbnet<33> cbnet<32> cbnet<31> cbnet<30> cbnet<29>
+cbnet<28> cbnet<27> cbnet<26> cbnet<25> cbnet<24> cbnet<23>
+cbnet<22> cbnet<21> cbnet<20> cbnet<19> cbnet<18> cbnet<17>
+cbnet<16> cbnet<15> cbnet<14> cbnet<13> cbnet<12> cbnet<11>
+cbnet<10> cbnet<9> cbnet<8> cbnet<7> cbnet<6> cbnet<5> cbnet<4>
+cbnet<3> cbnet<2> cbnet<1> cbnet<0> o_b por_b_vccaux por_b_vcco
+tstateb vccaux vcco io tsb_s<0> cnnd<13> cnnd<12> cnnd<11>
+cnnd<10> cnnd<9> cnnd<8> cnnd<7> cnnd<6> cnnd<5> cnnd<4> cnnd<3>
+cnnd<2> cnnd<1> cnnd<0> cnpd<19> cnpd<18> cnpd<17> cnpd<16>
+cnpd<15> cnpd<14> cnpd<13> cnpd<12> cnpd<11> cnpd<10> cnpd<9>
+cnpd<8> cnpd<7> cnpd<6> cnpd<5> cnpd<4> cnpd<3> cnpd<2> cnpd<1>
+cnpd<0>
.prot FREELIB
7W.MJ-%\(9[(JhVW!MXzT%V4:K3zT%m3P+XAX#<2_U/Q$S0 9xR)sp#/[=2'#j-Ey
8>/80S1M[)2[-\) HU:%7GF+*7c5e1w%-[(jw-Lv9>/80S1C$)2[-\) H%y%[
a/[=2'#bRE:K3zT%mU>+XAX#<2_'uQ$S0 9xRj5p#/[=2'#b3E:K3zT%mU(+Z
$[-\) H e%7GF+*7c7>1w%-[(jw3Jv9>/80S132)2[-\) H +%7GF+*7c7H1q
$K3zT%mpm+XAX#<2_[%Q$S0 9xRh7p#/[=2'#=JE:K3zT%m,V9>/80s1e+XAX#<2_$)0
oS0 9xRY%7gf+*7C0p#/[=2'#h1W%-[(JW;E:K3zT%mUV9>/80s13+XAX#<2_/)2<9ZW6b00
oM/f:\P $+ZK:].3.-/Y%K.2J9s$ *32<Sg$R3Xp[STW2M6GX69/%54f$%ZfqbR:%79K<6
:A8#D13U)2[#\;_[%Q$S\ oh h%7g +%RhPp#/+=PC;p#/+=PC*p#/+=PC(p8
_%=[ #$1w%=[ #<1w%=[ #H1w%=[ #J1w%=[ #B1w%=[ #=1w%=[ #X1w%=$ #=]eY
8>Z6yMPE+xa8.d13$)2[#*;_[jq$s\TOH +%7G 2%rH)P#/+]pc7J1w%=$ #=-eY
8>Z6yMP3+xa8.d13/)2[#*;_()2[#*;_s)2[#*;_$)2[#*;_2)2[#*;_i)2[#*;_:)0
oS\tohuQ$S\toh%Q$S\toh Q$S\toh1Q$4TfqM4'X,wS%_DUH\/#+]Z
FhR*sO=d]t0*+:\0u$+zk:\p $+d;:\p $+zk:\0u$+G/098D$s0 9Xr)(P#/[=2'#J5eY
8>/80S1Ms)26m's[c-a[m#yO%xP/9##0-dm66d Q42(6[
+!+]6dJ[
.ends iob_outlogic_sim_inp
